// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbzmm87iRmxSCFjM0FSLVrt6UxLwpOf_8',
    appId: '1:380593861111:web:4e787ca09e04d2681e7ef2',
    messagingSenderId: '380593861111',
    projectId: 'fooddeliveryapp-8dd92',
    authDomain: 'fooddeliveryapp-8dd92.firebaseapp.com',
    storageBucket: 'fooddeliveryapp-8dd92.appspot.com',
    measurementId: 'G-37BV26PE9L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYhkFX_Vvw6zVaRjXoQPkoo7GNe2nke08',
    appId: '1:380593861111:android:b64f24741d6a25cd1e7ef2',
    messagingSenderId: '380593861111',
    projectId: 'fooddeliveryapp-8dd92',
    storageBucket: 'fooddeliveryapp-8dd92.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArWhu6HL2j1EhJyBHel3mQ7SaRKncf_vs',
    appId: '1:380593861111:ios:04d6e07ce01349b41e7ef2',
    messagingSenderId: '380593861111',
    projectId: 'fooddeliveryapp-8dd92',
    storageBucket: 'fooddeliveryapp-8dd92.appspot.com',
    iosClientId: '380593861111-3093snr776cpudtvuf61ijd5qk066tch.apps.googleusercontent.com',
    iosBundleId: 'com.example.monkeyAppDemo',
  );
}
